### ISSUE TITLE
Add --history-max to upgrade helm command

### ISSUE THREAD

**Issue by DeepaKulkarniNews** [CircleCI-Public/helm-orb#63]
Currently a default of 10 releases are stored in history, we want to be able to specify how many historical releases we need.

**Comment by brivu** [comment]
Hey @DeepaKulkarniNews, thanks for opening this issue. the `--history-max` is not a valid flag in the `helm upgrade` or `helm install` commands. If I am missing something, please feel free to reopen this issue and link me to some documentation. I'd be happy to take a look. Thanks!

**Comment by msabramo** [comment]
`--history-max` is an option in at least the latest versions of Helm.

See https://helm.sh/docs/helm/helm_upgrade/

I found this issue because I'm searching for the same thing. I just had a CircleCI deploy job fail because we exceeded the maximum number of secrets allotted to us in our Kubernetes namespace and this is because all of our releases ae storing 10 revisions of history, the default. I need to be able to specify a lower number.
